### ISSUE TITLE
axelor-development-kit  Compile error

### ISSUE THREAD

**Issue by zhangdongbao** [axelor/axelor-open-platform#19]
axelor-core\src\main\java\com\axelor\rpc\ContextHandler.java:316:
value = Collections2.transform((Collection<?>) value, transform::apply);
axelor-core\src\main\java\com\axelor\rpc\JsonContext.java:196: 	
.collect(Collectors.toList());
axelor-core\src\main\java\com\axelor\meta\schema\actions\ActionView.java:201:
return item instanceof Model && JPA.em().contains(item) ? Resource.toMapCompact(item) : item;
axelor-core\src\main\java\com\axelor\rpc\Resource.java:727
value = Collections2.transform((Collection<?>) value, input -> toMap(input, names));

**Comment by axeloradmin** [comment]
Please check [this doc](https://github.com/axelor/axelor-development-kit/blob/master/CONTRIBUTING.md#reporting-issues) for issue reporting guidelines and report again.
