### ISSUE TITLE
fetchOne() succeeds if more than one row is returned

### ISSUE THREAD

**Issue by laurentmartelli** [axelor/axelor-open-platform#2]
Query.fetchOne() should raise an exception if the query returns more than one row : it is dangerous to assume everything is OK when you expect one result and there are indeed several.

**Comment by axeloradmin** [comment]
It's designed to get the first matched record. We'll update method doc. We can introduce a new method `Query.fetchOnly()` or something similar for this case.

**Comment by laurentmartelli** [comment]
I would favor renaming the current implementation into `fetchFirst` and create a new one named `fetchSingle`. The names would better match the intent in my opinion.

**Comment by axeloradmin** [comment]
We can't rename `fetchOne`. It's intention is clear enough. BTW, you can still use standard JPA api instead like this:

```java
@Inject
Provider<EntityManager> emp;

@Transactional
public void doSomeThing() {
  EntityManager em = emp.get();
  // use em.createQuery(...)
  // use getFirstResult or getSingleResult depending on the case
}
```

This way your code would remain more portable and less prone to breaking changes.
