### ISSUE TITLE
Mass update doesn't work with NULL value.

### ISSUE THREAD

**Issue by ec-blue** [axelor/axelor-open-platform#24]
With mass update tool : Nothing happens when I try to set field(s) to null or when I try to update field(s) if the field(s) is/are null.

## Version
Built with ADK 5.0

## Reproduce the Error
Use mass update tool to set field(s) to null. Nothing happens.

## Suggest a Fix
https://github.com/axelor/axelor-development-kit/blob/ef9c88d55615396cb1734f003c53e979e2cba873/axelor-core/src/main/java/com/axelor/db/Query.java#L475

HQL request return no results if one of the two operands is null. SQL doesn't support "=/!= null". The only test for the absence of a value (NULL) is IS NULL or IS NOT NULL.
One solution might be to delete this condition in your where clause like in the previous version (ADK 4.0)

**Comment by gdu-axelor** [comment]
Fixed f45378eb92541926e6a633de18cc16e69d278c97
