### ISSUE TITLE
Collections should be initialized

### ISSUE THREAD

**Issue by beuss** [axelor/axelor-open-platform#29]
Entities collections are null upon creation which can lead to NPE in almost any manipulation in first save transaction.
Collections should either be initialized in generated constructor/fields or should be lazily initialized in getters (I'll opt for the first one)
Let me know if you want a PR on this

**Comment by beuss** [comment]
Nevermind, have be influenced by API misuse in quality module (calling getCollection().clear() instead of clearCollection()) (maybe getCollection() should return an unmodifiable collection though to avoid this kind of misuses, this would need 2 getters/setters (protected getCollectionInternal() for Hibernate and public getCollection with unmodifiable collection)

**Comment by axeloradmin** [comment]
We need hibernate collection proxies in adk to implement a generic way to update them. May be we'll provide guide lines for end-user (developers) usage.
