### ISSUE TITLE
Job - How to login

### ISSUE THREAD

**Issue by mrp14** [axelor/axelor-open-platform#3]
Hello,

I've created a Quartz job, and I'd like it to run authenticated.

I've tried to manually login : 

```
 UsernamePasswordToken token = new UsernamePasswordToken("user", "password");

            final Subject subject = SecurityUtils.getSubject();
            try {
                subject.login(token);
            } catch (AuthenticationException e) {
                throw e;
            }
```

But I get an exception : 

> Caused by: java.lang.IllegalArgumentException: SessionContext must be an HTTP compatible implementation.

I searched for a solution and realized that I should override Shiro's session Manager to use a DefaultWebSessionManager instance, instead of the ServletContainerSessionManager used by default. But I can't figure out how to do it.

How can I make my job to run authenticated ? 

Thanks.
Best regards,

**Comment by axeloradmin** [comment]
Not supported.  However, if you are using v4 or later you can use [AuditableRunner](../blob/master/axelor-core/src/main/java/com/axelor/auth/AuditableRunner.java) to run the job as "admin" user.

We'll provide a better way to specify a specific user in next release.
