### ISSUE TITLE
Transient fields cannot be displayed in grids

### ISSUE THREAD

**Issue by beuss** [axelor/axelor-open-platform#30]
When a field is declared as transient, it cannot be displayed on grids because of the use of a Selector that remove transient fields from Select. This should be either documented or the selector should be fixed to `select self` if any transient field is asked (fields could be filtered afterwards)

**Comment by axeloradmin** [comment]
What's your use case? The `transient` fields are meant for internal usage only.

**Comment by beuss** [comment]
Use case is to have display-only fields as transient rather than storing them in the database (with all related issues, like updating them when computing code changes, initializing values on already existing data when such a field is added and so on)

**Comment by axeloradmin** [comment]
We can't support this with current grid view implementation. We'll document it and may be in future we may reconsider adding support for transient fields.
