### ISSUE TITLE
Errors are not correctly displayed when editing o2m in popups

### ISSUE THREAD

**Issue by beuss** [axelor/axelor-open-platform#32]
When editing o2m, errors are silently ignored, no flash message appears, but popup isn't closed

Steps to reproduce:

- Create a quotation
- Launch new line popup
- Clear the Tax field
- Click OK

Expected behavior: a flash message "Tax field is required" should appear

**Comment by beuss** [comment]
This specific issue seems to be due to the fact that invalid field is taxEquiv which is hidden and not taxLine (whichg is shown)

**Comment by axeloradmin** [comment]
Already fixed.
