### ISSUE TITLE
gradle :database

### ISSUE THREAD

**Issue by Breggor** [axelor/axelor-open-platform#35]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':database'.
> Unable to find application config.

**Comment by axeloradmin** [comment]
The `database` task is introduced in v5 and uses `src/main/resources/application.properties` by default as app config. You can also provide custom location with `-Daxelor.config=<path>` option.

**Comment by axeloradmin** [comment]
Even the `database` task has it's own option `--config <path>`. Try this:

```
./gradlew database --config /path/to/your/application.properties
```

**Comment by webeasymail** [comment]
@axeloradmin ./gradlew database with no arguments or with the --config argument will result in an Unable to find application config. error, currently version 5.0.7, with no spaces in the path.

**Comment by webeasymail** [comment]
The operating system is win10

**Comment by MkkOF** [comment]
i have met the same problem. unsolved.
