### ISSUE TITLE
I18nBundle should override containsKey

### ISSUE THREAD

**Issue by beuss** [axelor/axelor-open-platform#38]
If a given key does not exists in the translation, the key itself is returned (as per handleGetObject implementation), however, when using containsKey, parent bundle (empty locale) is checked triggering a dummy load, which can be problematic when using the bundle in a JPA.jdbcWork block.

**Comment by axeloradmin** [comment]
Would you please provide some more details like what issues you are facing. The bundle is populated lazily, however the `load()` method will only do actual loading once.

**Comment by beuss** [comment]
Not for the empty locale as there is no translation for it in the DB so its map is always empty triggering a load.
Issue is when passing the bundle to some code that shouldn't access to database (eg. a jasper reports template run in jdbcWork), the JPA load will miserabily fail.
If you override the default behavior of looking at the parent bundle on handleGetObject, then you should override it in containsKey too as you might end up in a situation where calling containsKey returns true (because the key is missing in child bundle but not in parent one) but get returns the key itself as the parent querying has been disabled.

**Comment by axeloradmin** [comment]
Even if we override `containsKey`, we still have to load messages. So not sure whether the changes fixes your issue.

**Comment by beuss** [comment]
Yes it should, since you don't call parent bundle through containsKey. It is likely that values will already be loaded before the jdbcWork for current user's locale

**Comment by axeloradmin** [comment]
Fixed in dev branch.
