### ISSUE TITLE
How to deploy abs-webapp on jboss eap 7

### ISSUE THREAD

**Issue by minhtuanvu** [axelor/axelor-open-platform#4]
As I have seen on the home page there is said that adk has support for jboss, but I can not install successfully.

There are many error messages as follows:

16:30:12,844 ERROR [org.jboss.as.controller.management-operation] (DeploymentScanner-threads - 2) WFLYCTL0013: Operation ("full-replace-deployment")
failed - address: ([]) - failure description: {"WFLYCTL0080: Failed services" => {"jboss.persistenceunit.\"abs-webapp-4.0.0.war#persistenceUnit\"" => "org.jboss.msc.service.StartException in service jboss.persistenceunit.\"abs-webapp-4.0.0.war#persistenceUnit\": org.hibernate.AnnotationException:
@OneToOne or @ManyToOne on com.axelor.apps.base.db.Company.address references an unknown entity: com.axelor.apps.base.db.Address
Caused by: org.hibernate.AnnotationException: @OneToOne or @ManyToOne on com.axelor.apps.base.db.Company.address references an unknown entity: com.axelor.apps.base.db.Address"}}
16:30:12,946 INFO [org.jboss.as.server] (DeploymentScanner-threads - 2) WFLYSRV0016: Replaced deployment "abs-webapp-4.0.0.war" with deployment "abs-webapp-4.0.0.war"
16:30:12,955 INFO [org.jboss.as.controller] (DeploymentScanner-threads - 2) WFLYCTL0183: Service status report

**Comment by axeloradmin** [comment]
Not supported at the moment.
