### ISSUE TITLE
Field x-bind is invalid in grid

### ISSUE THREAD

**Issue by Breggor** [axelor/axelor-open-platform#40]
<grid name="account-grid" title="Accounting.Accounts" model="com.axelor.apps.account.db.Account">
        <field name="code" x-bind="{{code|unaccent|uppercase}}"/>
  </grid>
x-bind="{{code|unaccent|uppercase}}" is invalid

**Comment by axeloradmin** [comment]
The `x-bind` attribute is not supported on grid view. With current grid view implementation, it's difficult to add support for `x-bind`. We might consider it if we ever decide to re-implement grid widget.
