### ISSUE TITLE
If the field of enum type is used to control other fields to show or hide

### ISSUE THREAD

**Issue by webeasymail** [axelor/axelor-open-platform#41]
In the document, I introduced https://docs.axelor.com/adk/5.0/dev-guide/models/models.html. I introduced the usage of enum. If I want to control the filed display hiding according to the value of enum, how should I write it? ? I follow the example of showIf=“status == OrderStatus.OPEN” and found that it does not take effect.

**Comment by beuss** [comment]
Try with string, something like ``showIf="status == 'OPEN'"`` this should do it

**Comment by webeasymail** [comment]
@beuss thank you very much
