### ISSUE TITLE
Eclipse Setup Document

### ISSUE THREAD

**Issue by guponnus** [axelor/axelor-open-platform#5]
Hi,

Can you please provides the steps to configure the Development Env in Eclipse?

**Comment by guponnus** [comment]
Have changed the view xml files but its not reflecting after restarting the app server.

**Comment by drik** [comment]
Here is the one I followed : http://docs.axelor.com/adk/latest/getting_started/eclipse.html

**Comment by axeloradmin** [comment]
https://docs.axelor.com/adk/5.0/getting-started/eclipse.html
