### ISSUE TITLE
axelor: command not found

### ISSUE THREAD

**Issue by Thiru-L** [axelor/axelor-open-platform#53]
Hi,

Link : https://docs.axelor.com/adk/4.0/getting-started/install/linux.html

I use the above link to try to install Axelor.After completing Export Axelor path i getting error like "axelor:command not found".

Can you provide some tutorial for Axelor installation & new project creation.thanks

> Note : Kindly update your documentation with latest links.when i try to redirect a page with github link it returns "Page not found" error.

My system Config : 

1.Ubuntu 18.04 LTS - 64-bit,

Kindly check this link for more Info : https://ibb.co/VNbhqTW

**Comment by axeloradmin** [comment]
For new project, we recommend version 5.0. The 4.0 docs is not up-to-date and pointing to the git repository with latest sources.

Follow the latest 5.0 quickstart here: https://docs.axelor.com/adk/5.0/getting-started/install.html
