### ISSUE TITLE
axelor is not recognised

### ISSUE THREAD

**Issue by akhilsahu** [axelor/axelor-open-platform#6]
I followed following steps

Windows
In this chapter we will see how to prepare the development environment on Windows operating system for working with Axelor Development Kit sources.

Prerequisite

JDK 1.7
PostgreSQL 9.x
Git for Windows
JDK

Download the JDK installer from the above link and install on your system.

Once installed, set the environment variables as follows:

> set JAVA_HOME=C:\path\to\jdk
> set PATH=%JAVA_HOME%\bin;%PATH%
Generally, the JDK installer sets these variables. So skip if it’s done.

PostgreSQL

Download the PostgreSQL from the above link and install on your system.

Git for Windows

Install the Git for windows from the above link.

Installation

Download the latest distribution package from https://github.com/axelor/axelor-development-kit/releases and extract the package somewhere and set following environment variables.

> set AXELOR_HOME=C:\path\to\axelor-adk
> set PATH=%AXELOR_HOME%\bin;%PATH%
or you can build from the latest source like this:

> git clone https://github.com/axelor/axelor-development-kit.git
> cd axelor-development-kit
> gradlew installApp
> set AXELOR_HOME=C:\path\to\axelor-development-kit\build\install\axelor-development-kit
> set PATH=%AXELOR_HOME$\bin;%PATH%
You should have a special command `axelor' in your path now. Just try issuing following command on the terminal:

> axelor --help

But still it results to 

Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\Users\lenovo>git
usage: git [--version] [--help] [-C <path>] [-c name=value]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p | --paginate | --no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]

These are common Git commands used in various situations:

start a working area (see also: git help tutorial)
   clone      Clone a repository into a new directory
   init       Create an empty Git repository or reinitialize an existing one

work on the current change (see also: git help everyday)
   add        Add file contents to the index
   mv         Move or rename a file, a directory, or a symlink
   reset      Reset current HEAD to the specified state
   rm         Remove files from the working tree and from the index

examine the history and state (see also: git help revisions)
   bisect     Use binary search to find the commit that introduced a bug
   grep       Print lines matching a pattern
   log        Show commit logs
   show       Show various types of objects
   status     Show the working tree status

grow, mark and tweak your common history
   branch     List, create, or delete branches
   checkout   Switch branches or restore working tree files
   commit     Record changes to the repository
   diff       Show changes between commits, commit and working tree, etc
   merge      Join two or more development histories together
   rebase     Reapply commits on top of another base tip
   tag        Create, list, delete or verify a tag object signed with GPG

collaborate (see also: git help workflows)
   fetch      Download objects and refs from another repository
   pull       Fetch from and integrate with another repository or a local branch
   push       Update remote refs along with associated objects

'git help -a' and 'git help -g' list available subcommands and some
concept guides. See 'git help <command>' or 'git help <concept>'
to read about a specific subcommand or concept.

C:\Users\lenovo> git clone https://github.com/axelor/axelor-development-kit.git
Cloning into 'axelor-development-kit'...
remote: Counting objects: 74034, done.
remote: Total 74034 (delta 0), reused 0 (delta 0), pack-reused 74034
Receiving objects: 100% (74034/74034), 14.19 MiB | 1.20 MiB/s, done.
Resolving deltas: 100% (42382/42382), done.

C:\Users\lenovo>cd axe-development-kit
The system cannot find the path specified.

C:\Users\lenovo>cd axelor-development-kit

C:\Users\lenovo\axelor-development-kit>gradlew installApp
:buildSrc:clean UP-TO-DATE
:buildSrc:axelor-common:clean UP-TO-DATE
:buildSrc:axelor-gradle:clean UP-TO-DATE
:buildSrc:compileJava UP-TO-DATE
:buildSrc:compileGroovy SKIPPED
:buildSrc:processResources UP-TO-DATE
:buildSrc:classes UP-TO-DATE
:buildSrc:jar
:buildSrc:assemble
:buildSrc:compileTestJava UP-TO-DATE
:buildSrc:compileTestGroovy UP-TO-DATE
:buildSrc:processTestResources UP-TO-DATE
:buildSrc:testClasses UP-TO-DATE
:buildSrc:axelor-common:updateVersion SKIPPED
:buildSrc:axelor-common:compileJava
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
:buildSrc:axelor-common:processResources
:buildSrc:axelor-common:classes
:buildSrc:axelor-common:jar
:buildSrc:axelor-gradle:compileJava UP-TO-DATE
:buildSrc:axelor-gradle:compileGroovy
:buildSrc:axelor-gradle:processResources
:buildSrc:axelor-gradle:classes
:buildSrc:axelor-gradle:jar
:buildSrc:test UP-TO-DATE
:buildSrc:check UP-TO-DATE
:buildSrc:build
:buildSrc:axelor-common:assemble
:buildSrc:axelor-common:compileTestJava
:buildSrc:axelor-common:processTestResources
:buildSrc:axelor-common:testClasses
:buildSrc:axelor-common:test SKIPPED
:buildSrc:axelor-common:check UP-TO-DATE
:buildSrc:axelor-common:build
:buildSrc:axelor-gradle:assemble
:buildSrc:axelor-gradle:compileTestJava
:buildSrc:axelor-gradle:compileTestGroovy UP-TO-DATE
:buildSrc:axelor-gradle:processTestResources
:buildSrc:axelor-gradle:testClasses
:buildSrc:axelor-gradle:test SKIPPED
:buildSrc:axelor-gradle:check UP-TO-DATE
:buildSrc:axelor-gradle:build
:axelor-common:updateVersion SKIPPED
:axelor-common:compileJava
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
:axelor-common:processResources
:axelor-common:classes
:axelor-common:jar
:axelor-shell:compileJava
:axelor-shell:processResources
:axelor-shell:classes
:axelor-shell:jar
:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:jar SKIPPED
:axelor-common:generatePomFileForMavenJavaPublication
:axelor-common:publishMavenJavaPublicationToAdkRepository
Could not find metadata com.axelor:axelor-common/maven-metadata.xml in remote (file:/C:/Users/lenovo/axelor-development-kit/build/dist/maven)
:axelor-common:publish
:axelor-core:generatePomFileForMavenJavaPublication
:axelor-core:generateCode
:axelor-core:licenseFormatGenerated
:axelor-core:compileJava
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
:axelor-core:processResources
:axelor-core:classes
:axelor-core:jar
:axelor-core:publishMavenJavaPublicationToAdkRepository
Could not find metadata com.axelor:axelor-core/maven-metadata.xml in remote (file:/C:/Users/lenovo/axelor-development-kit/build/dist/maven/)
:axelor-core:publish
:axelor-gradle:compileJava UP-TO-DATE
:axelor-gradle:compileGroovy
:axelor-gradle:processResources
:axelor-gradle:classes
:axelor-gradle:jar
:axelor-gradle:dist
:axelor-gradle:generatePomFileForMavenJavaPublication
:axelor-gradle:publishMavenJavaPublicationToAdkRepository
Could not find metadata com.axelor:axelor-gradle/maven-metadata.xml in remote (file:/C:/Users/lenovo/axelor-development-kit/build/dist/maven/)
:axelor-gradle:publish
:axelor-shell:generatePomFileForMavenJavaPublication
:axelor-shell:publishMavenJavaPublicationToAdkRepository
Could not find metadata com.axelor:axelor-shell/maven-metadata.xml in remote (file:/C:/Users/lenovo/axelor-development-kit/build/dist/maven/)
:axelor-shell:publish
:axelor-test:generatePomFileForMavenJavaPublication
:axelor-test:compileJava
:axelor-test:processResources UP-TO-DATE
:axelor-test:classes
:axelor-test:jar
:axelor-test:publishMavenJavaPublicationToAdkRepository
Could not find metadata com.axelor:axelor-test/maven-metadata.xml in remote (file:/C:/Users/lenovo/axelor-development-kit/build/dist/maven/)
:axelor-test:publish
:axelor-web:generatePomFileForMavenJavaPublication
:axelor-web:generateCode
:axelor-web:licenseFormatGenerated UP-TO-DATE
:axelor-web:compileJava
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
:axelor-web:processResources
:axelor-web:classes
:axelor-web:jar
:axelor-web:publishMavenJavaPublicationToAdkRepository
Could not find metadata com.axelor:axelor-web/maven-metadata.xml in remote (file:/C:/Users/lenovo/axelor-development-kit/build/dist/maven/)
:axelor-web:publish
:repo
:startScripts
:installApp
The installApp task has been deprecated and is scheduled to be removed in Gradle 3.0. Please use the installDist task instead.

BUILD SUCCESSFUL

Total time: 2 mins 23.105 secs
C:\Users\lenovo\axelor-development-kit> set AXELOR_HOME=C:\Users\lenovo\axelor-development-kit\build\install\axelor-development-kit

C:\Users\lenovo\axelor-development-kit>set PATH=%AXELOR_HOME$\bin;%PATH%

C:\Users\lenovo\axelor-development-kit>axelor --help
'axelor' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\lenovo\axelor-development-kit>

**Comment by guponnus** [comment]
Hi,

Thank you so much, can you please share the steps to configure Eclipse?

**Comment by akhilsahu** [comment]
C:\Users\lenovo> git clone https://github.com/axelor/axelor-development-kit.git
Cloning into 'axelor-development-kit'...
remote: Counting objects: 74034, done.
remote: Total 74034 (delta 0), reused 0 (delta 0), pack-reused 74034
Receiving objects: 100% (74034/74034), 14.19 MiB | 1.20 MiB/s, done.
Resolving deltas: 100% (42382/42382), done.

C:\Users\lenovo>cd axe-development-kit
The system cannot find the path specified.

C:\Users\lenovo>cd axelor-development-kit

C:\Users\lenovo\axelor-development-kit>gradlew installApp
:buildSrc:clean UP-TO-DATE
:buildSrc:axelor-common:clean UP-TO-DATE
:buildSrc:axelor-gradle:clean UP-TO-DATE
:buildSrc:compileJava UP-TO-DATE
:buildSrc:compileGroovy SKIPPED
:buildSrc:processResources UP-TO-DATE
:buildSrc:classes UP-TO-DATE
:buildSrc:jar
:buildSrc:assemble
:buildSrc:compileTestJava UP-TO-DATE
:buildSrc:compileTestGroovy UP-TO-DATE
:buildSrc:processTestResources UP-TO-DATE
:buildSrc:testClasses UP-TO-DATE
:buildSrc:axelor-common:updateVersion SKIPPED
:buildSrc:axelor-common:compileJava
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
:buildSrc:axelor-common:processResources
:buildSrc:axelor-common:classes
:buildSrc:axelor-common:jar
:buildSrc:axelor-gradle:compileJava UP-TO-DATE
:buildSrc:axelor-gradle:compileGroovy
:buildSrc:axelor-gradle:processResources
:buildSrc:axelor-gradle:classes
:buildSrc:axelor-gradle:jar
:buildSrc:test UP-TO-DATE
:buildSrc:check UP-TO-DATE
:buildSrc:build
:buildSrc:axelor-common:assemble
:buildSrc:axelor-common:compileTestJava
:buildSrc:axelor-common:processTestResources
:buildSrc:axelor-common:testClasses
:buildSrc:axelor-common:test SKIPPED
:buildSrc:axelor-common:check UP-TO-DATE
:buildSrc:axelor-common:build
:buildSrc:axelor-gradle:assemble
:buildSrc:axelor-gradle:compileTestJava
:buildSrc:axelor-gradle:compileTestGroovy UP-TO-DATE
:buildSrc:axelor-gradle:processTestResources
:buildSrc:axelor-gradle:testClasses
:buildSrc:axelor-gradle:test SKIPPED
:buildSrc:axelor-gradle:check UP-TO-DATE
:buildSrc:axelor-gradle:build
:axelor-common:updateVersion SKIPPED
:axelor-common:compileJava
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
:axelor-common:processResources
:axelor-common:classes
:axelor-common:jar
:axelor-shell:compileJava
:axelor-shell:processResources
:axelor-shell:classes
:axelor-shell:jar
:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:jar SKIPPED
:axelor-common:generatePomFileForMavenJavaPublication
:axelor-common:publishMavenJavaPublicationToAdkRepository
Could not find metadata com.axelor:axelor-common/maven-metadata.xml in remote (file:/C:/Users/lenovo/axelor-development-kit/build/dist/maven)
:axelor-common:publish
:axelor-core:generatePomFileForMavenJavaPublication
:axelor-core:generateCode
:axelor-core:licenseFormatGenerated
:axelor-core:compileJava
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
:axelor-core:processResources
:axelor-core:classes
:axelor-core:jar
:axelor-core:publishMavenJavaPublicationToAdkRepository
Could not find metadata com.axelor:axelor-core/maven-metadata.xml in remote (file:/C:/Users/lenovo/axelor-development-kit/build/dist/maven/)
:axelor-core:publish
:axelor-gradle:compileJava UP-TO-DATE
:axelor-gradle:compileGroovy
:axelor-gradle:processResources
:axelor-gradle:classes
:axelor-gradle:jar
:axelor-gradle:dist
:axelor-gradle:generatePomFileForMavenJavaPublication
:axelor-gradle:publishMavenJavaPublicationToAdkRepository
Could not find metadata com.axelor:axelor-gradle/maven-metadata.xml in remote (file:/C:/Users/lenovo/axelor-development-kit/build/dist/maven/)
:axelor-gradle:publish
:axelor-shell:generatePomFileForMavenJavaPublication
:axelor-shell:publishMavenJavaPublicationToAdkRepository
Could not find metadata com.axelor:axelor-shell/maven-metadata.xml in remote (file:/C:/Users/lenovo/axelor-development-kit/build/dist/maven/)
:axelor-shell:publish
:axelor-test:generatePomFileForMavenJavaPublication
:axelor-test:compileJava
:axelor-test:processResources UP-TO-DATE
:axelor-test:classes
:axelor-test:jar
:axelor-test:publishMavenJavaPublicationToAdkRepository
Could not find metadata com.axelor:axelor-test/maven-metadata.xml in remote (file:/C:/Users/lenovo/axelor-development-kit/build/dist/maven/)
:axelor-test:publish
:axelor-web:generatePomFileForMavenJavaPublication
:axelor-web:generateCode
:axelor-web:licenseFormatGenerated UP-TO-DATE
:axelor-web:compileJava
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
:axelor-web:processResources
:axelor-web:classes
:axelor-web:jar
:axelor-web:publishMavenJavaPublicationToAdkRepository
Could not find metadata com.axelor:axelor-web/maven-metadata.xml in remote (file:/C:/Users/lenovo/axelor-development-kit/build/dist/maven/)
:axelor-web:publish
:repo
:startScripts
:installApp
The installApp task has been deprecated and is scheduled to be removed in Gradle 3.0. Please use the installDist task instead.

BUILD SUCCESSFUL

Total time: 2 mins 23.105 secs
C:\Users\lenovo\axelor-development-kit> set AXELOR_HOME=C:\Users\lenovo\axelor-development-kit\build\install\axelor-development-kit

C:\Users\lenovo\axelor-development-kit>set PATH=%AXELOR_HOME$\bin;%PATH%

C:\Users\lenovo\axelor-development-kit>axelor --help
'axelor' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\lenovo\axelor-development-kit>

**Comment by guponnus** [comment]
Hi, thank you.

Do u have steps to configure the Eclipse?

**Comment by akhilsahu** [comment]
I am working on cmd here rather I also tried it using Eclise which too failed
I build it using gradle command for setting it up for workspace. Using
` ./gradlew generateCode cleanEclipse eclipse`
I installed the web perspective. Then i CONFIGURED IT to apache 7.
I ran it then .Please check this issue for furthur reference [https://github.com/axelor/axelor-demo/issues/3](issue)

**Comment by akhilsahu** [comment]
Followed this http://docs.axelor.com/adk/latest/getting_started/eclipse.html

**Comment by guponnus** [comment]
Ok.... me too followed the same link. somehow i am able to run it from Eclipse but not sure the correct way of doing so asking.

**Comment by akhilsahu** [comment]
Thats only way i think. can you please tell whether this be converted into a desktop app

**Comment by guponnus** [comment]
its web application. u mean standalone desktop app? if yes no.

**Comment by akhilsahu** [comment]
OK Can you please tell where I am wrong with this   https://github.com/axelor/axelor-demo/issues/3

Tried to build on axelor

**Comment by 719923505** [comment]
there is no folder install in export AXELOR_HOME.


install Dist sometimes,then it appears and it works.

**Comment by halkhalil** [comment]
for version 5 of ADk there is installDist ?

**Comment by axeloradmin** [comment]
ADK v5 has dropped CLI tool, so `axelor` command is no longer available and thus no `installDist` task too.
