### ISSUE TITLE
Build only one module

### ISSUE THREAD

**Issue by Elikill58** [axelor/axelor-open-platform#70]
Hi,
I would like to generate code only to one module then generate jar only for it, to keep some time.
Because now, I have to build ALL modules, which take too long time.

**Comment by Cedric-Guerrier** [comment]
Hi,
I've the same need for making custom module.

Regards.

**Comment by Elikill58** [comment]
Fixed thanks to this post :
https://forum.axelor.com/t/module-non-utilise/3387/6
