### ISSUE TITLE
Toolbar - Panel Dashlet

### ISSUE THREAD

**Issue by Cedric-Guerrier** [axelor/axelor-open-platform#86]
Hi,

With Axelor Open Platform and new support for toolbar and menubar on dashlet and o2m/m2m widgets in 5.4, buttons in toolbar are replicated in all panel-dashlet.

![image](https://user-images.githubusercontent.com/46818519/104015022-52337800-51b4-11eb-9176-91dd7f9d9ec3.png)

Axelor Open Platform version 5.4.0

Regards

**Comment by pdo-axelor** [comment]
Please check if it's fixed since https://github.com/axelor/axelor-open-platform/commit/89487eb2a278c63a478782deb5c1a6dd88db4262

**Comment by Cedric-Guerrier** [comment]
Seems to be ok with 5.4.2
